### ISSUE TITLE
ACCESS1.0 files not being returned

### ISSUE THREAD

**Issue by ScottWales** [coecms/clef#53] opened 2018-12-04 03:13 UTC
The following search is returning no output
```
(clef-test) saw562@vdi-n4 ~ $ clef cmip5 --variable tasmin --experiment historical --table Amon -m ACCESS1.0

Everything available on ESGF is also available locally
(clef-test) saw562@vdi-n4 ~ $ 
```

**Comment by paolap** [comment] 2018-12-04 03:50
I noticed that too! In my case (I will try to reproduce) it was saying the ACCESS1.0 was missing.
I think it must be a name model translation, not sure we included that yet. I will try to fix that and see if that fixes it.

**Comment by paolap** [comment] 2018-12-06 00:49
This should be solved at least momentarily.
It was caused by line 275 in cli.py, which I commented

ql = ql.join(Path.c5dataset).filter(C5Dataset.project==project)

The first ql has all the expected results, but the filter on the second line returns nothing
So there's no paths to print at the end of the search however clef says correctly everything is available locally. 
I think this was introduced to stop clef returning records in rr3 which weren't CMIP5 but CORDEX.
This might re-appear now or was potentially solved at view/table level. Once we're sure of that we can close this issue.

**Closed** 2018-12-14 03:35 UTC
