### ISSUE TITLE
Dots and dashes in model names

### ISSUE THREAD

**Issue by DamienIrving** [coecms/clef#82] opened 2019-08-06 00:50 UTC
This is a very minor comment, but I've noticed that at the command line clef works fine with either dashes or dots between the numbers in model names, e.g.
`CSIRO-Mk3.6.0`
`CSIRO-Mk3-6-0`

whereas when using `import clef.code` within a script it only accepts dots. 

It probably wouldn't really matter except that the official model ids use dashes, so your first instinct as a user is to use `CSIRO-Mk3-6-0`.

**Comment by paolap** [comment] 2019-08-06 01:21
Hi Damien,

did you use the latest clef?
We've released a new version last week (0.5.0) which is analysis3 and we're going to release probably a new one this week.

**Comment by DamienIrving** [comment] 2019-08-06 01:24
@paolap Yep, I used version 0.5.0.

**Comment by paolap** [comment] 2019-08-06 01:32
Hi Damien I can't reproduce your issue, what occurs to me is that maybe you're using directly the 'local_query' function rather than 'search' which calls other functions before to check the arguments and values you're passing and fixes them if they need to.

We've also updated the read the docs now so there shouldn't be confusion anymore.
Could you confirm with me if that's the case, otherwise could you post the exact code you're using?
Thanks

**Comment by DamienIrving** [comment] 2019-08-06 05:24
No problem. Following [this example](https://clef.readthedocs.io/en/stable/code.html) I did the following:

```
>>> import clef.code
>>> db = clef.code.connect()
>>> session = clef.code.Session()

>>> constraints_dash = {'variable': 'masso', 'model': 'ACCESS1-3', 'table': 'Omon', 'experiment': 'piControl', 'ensemble': 'r1i1p1'}
>>> clef.code.search(session, project='cmip5', **constraints_dash)
[]

>>> constraints_dot = {'variable': 'masso', 'model': 'ACCESS1.3', 'table': 'Omon', 'experiment': 'piControl', 'ensemble': 'r1i1p1'}
>>> clef.code.search(session, project='cmip5', **constraints_dot)
[{'filenames': ['masso_Omon_ACCESS1-3_piControl_r1i1p1_050001-074912.nc',
   'masso_Omon_ACCESS1-3_piControl_r1i1p1_025001-049912.nc'],
  'project': 'CMIP5',
  'institute': 'CSIRO-BOM',
  'model': 'ACCESS1.3',
  'experiment': 'piControl',
  'frequency': 'mon',
  'realm': 'ocean',
  'r': '1',
  'i': '1',
  'p': '1',
  'ensemble': 'r1i1p1',
  'cmor_table': 'Omon',
  'version': None,
  'variable': 'masso',
  'pdir': '/g/data1/rr3/publications/CMIP5/output1/CSIRO-BOM/ACCESS1-3/piControl/mon/ocean/Omon/r1i1p1/latest/masso',
  'periods': [('50001', '74912'), ('25001', '49912')],
  'fdate': '25001',
  'tdate': '74912',
  'time_complete': None}]
```

**Comment by paolap** [comment] 2019-08-06 07:15
It's weird for some reason the master branch we used had a faulty version you can see here:

if 'model' in args.keys():
        fix_model(project, args['model'])

should be 

if 'model' in args.keys():
        args['model'] = fix_model(project, args['model'])

we're calling the function but we don't update the value. This have been deleted accidentally at some stage in one of the branches we merged, because my version still has the right syntax and no change has been done on this for a while. Thanks for getting back to me, I'll add this to the fixes for tomorrow.
I will also try to add a test for this so we make sure we don't messed it up again

**Comment by DamienIrving** [comment] 2019-08-06 21:53
Thanks, @paolap

**Comment by paolap** [comment] 2019-08-09 05:58
This is now solved in localfix, I also noticed alternative model names weren't working for --remote option, they now work for everything.

**Closed** 2019-08-16 03:47 UTC
